# dataset
data_path: "./data"
#filename: "sdwpf_baidukddcup2022_full.csv"
filename: "wtbdata_245days.csv"
input_len: 144 
output_len: 288
# var_len: 13
var_len: 10
capacity: 134
patient: 2 
only_useful: True
train_days: 214 
val_days: 16 
test_days: 15 
total_days: 245 
gpu_id: 2
seed: 0
best: 7
num_workers: 18
batch_size: 32 
# output_path: "./output/"
num_workers: 18
epoch: 10 
batch_size: 32 
output_path: "./output/baseline"
log_per_steps: 100
lr: 0.00005
clip_norm: 5
weight_decay: 0
learner: "adam"
lr_decay: False
lr_scheduler_type: None
lr_eta_min: 0.00001
lr_decay_ratio: 0.1
lr_warmup_epoch: 5
lr_warmup_init: 0.000001
model: WPFModel
hidden_dims: 128 
nhead: 8
dropout: 0.5
encoder_layers: 2
decoder_layers: 1
gsteps: 1
loss: "FilterMSELoss"
# loss: "MSELoss"